
services:
 adminer-service:
  image: adminer
  restart: unless-stopped
  container_name: adminer
  depends_on:
   - postgres-service
  networks:
   - 
  ports:
   - "8080:8080"
  environment:
   - ADMINER_DESIGN=pepa-linha-dark

 fastapi-service:
  build:
   context: .
   dockerfile: Dockerfile
  image: fastapi
  container_name: fastapi
  restart: unless-stopped
  depends_on:
   - postgres-service
  ports:
   - "8000:8000"
  environment:
   - POSTGRES_SERVER=postgres
   - POSTGRES_PORT=${POSTGRES_PORT}
   - POSTGRES_DB=${POSTGRES_DB}
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=
  networks:
   - 
  volumes:
   - ".:/app"
  # command: "./startup.sh"

 smtp-service:
  image: axllent/mailpit
  restart: unless-stopped
  container_name: smtp
  networks:
   - 
  ports:
   - "8025:8025"
   - "1025:1025"

 postgres-service:
  image: postgres:17
  container_name: postgres
  environment:
   - POSTGRES_USER=
   - POSTGRES_PASSWORD=
   - POSTGRES_DB=
  networks:
   - 
  volumes:
   - 

networks:
volumes:
  external: true
