"""Creación de tablas

Revision ID: 32675ce03817
Revises: 
Create Date: 2024-10-14 16:37:10.659155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32675ce03817'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_units',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('acronym', sa.String(length=3), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_business_units_uuid'), 'business_units', ['uuid'], unique=False)
    op.create_table('disciplines',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('acronym', sa.String(length=3), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_disciplines_uuid'), 'disciplines', ['uuid'], unique=False)
    op.create_table('documents_types',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('acronym', sa.String(length=3), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_documents_types_uuid'), 'documents_types', ['uuid'], unique=False)
    op.create_table('files',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=150), nullable=True),
    sa.Column('ext', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('folder', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=125), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_files_created_by'), 'files', ['created_by'], unique=False)
    op.create_index(op.f('ix_files_uuid'), 'files', ['uuid'], unique=False)
    op.create_table('managements_areas',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('acronym', sa.String(length=3), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_managements_areas_uuid'), 'managements_areas', ['uuid'], unique=False)
    op.create_table('documents',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('document_type_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('nro', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_uuid'], ['documents_types.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_documents_uuid'), 'documents', ['uuid'], unique=False)
    op.create_table('documents_versions',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('file_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('document_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_uuid'], ['documents.uuid'], ),
    sa.ForeignKeyConstraint(['file_uuid'], ['files.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_documents_versions_uuid'), 'documents_versions', ['uuid'], unique=False)
    op.create_table('project_document',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('business_unit_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('ceco', sa.String(length=255), nullable=True),
    sa.Column('management_area_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('document_version_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('discipline_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('correlative', sa.Integer(), nullable=True),
    sa.Column('correlative_automatic', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_unit_uuid'], ['business_units.uuid'], ),
    sa.ForeignKeyConstraint(['discipline_uuid'], ['disciplines.uuid'], ),
    sa.ForeignKeyConstraint(['document_version_uuid'], ['documents_versions.uuid'], ),
    sa.ForeignKeyConstraint(['management_area_uuid'], ['managements_areas.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_project_document_uuid'), 'project_document', ['uuid'], unique=False)
    op.create_table('project_documents_correlative',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('project_document_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('file_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('correlative', sa.Integer(), nullable=True),
    sa.Column('upload_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_uuid'], ['files.uuid'], ),
    sa.ForeignKeyConstraint(['project_document_uuid'], ['project_document.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_project_documents_correlative_uuid'), 'project_documents_correlative', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_documents_correlative_uuid'), table_name='project_documents_correlative')
    op.drop_table('project_documents_correlative')
    op.drop_index(op.f('ix_project_document_uuid'), table_name='project_document')
    op.drop_table('project_document')
    op.drop_index(op.f('ix_documents_versions_uuid'), table_name='documents_versions')
    op.drop_table('documents_versions')
    op.drop_index(op.f('ix_documents_uuid'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_managements_areas_uuid'), table_name='managements_areas')
    op.drop_table('managements_areas')
    op.drop_index(op.f('ix_files_uuid'), table_name='files')
    op.drop_index(op.f('ix_files_created_by'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_documents_types_uuid'), table_name='documents_types')
    op.drop_table('documents_types')
    op.drop_index(op.f('ix_disciplines_uuid'), table_name='disciplines')
    op.drop_table('disciplines')
    op.drop_index(op.f('ix_business_units_uuid'), table_name='business_units')
    op.drop_table('business_units')
    # ### end Alembic commands ###