"""Creación de Optional en tablas

Revision ID: 3461cddc1572
Revises: f6501bbe96fa
Create Date: 2024-10-22 20:54:58.357657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3461cddc1572'
down_revision: Union[str, None] = 'f6501bbe96fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###