"""nuevas migraciones y columnas

Revision ID: 3abecfed5afb
Revises: 4cf0fc40db9b
Create Date: 2024-10-27 17:10:33.785185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abecfed5afb'
down_revision: Union[str, None] = '4cf0fc40db9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('business_unit_uuid', sa.UUID(as_uuid=150), nullable=True))
    op.create_foreign_key(None, 'disciplines', 'business_units', ['business_unit_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disciplines', type_='foreignkey')
    op.drop_column('disciplines', 'business_unit_uuid')
    # ### end Alembic commands ###