"""name deleted of document_version

Revision ID: 54eb5c55dcd5
Revises: 07b953825733
Create Date: 2024-11-22 19:01:34.749318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54eb5c55dcd5'
down_revision: Union[str, None] = '07b953825733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_units', 'name')
    op.drop_column('documents_versions', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_versions', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('business_units', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###