"""no uuid to disciplines and array 

Revision ID: 73efc0ee0fa9
Revises: c24e6487f303
Create Date: 2024-11-13 21:24:31.948555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73efc0ee0fa9'
down_revision: Union[str, None] = 'c24e6487f303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###