"""Adding files correlative_logs

Revision ID: 7bd89cf527a3
Revises: ef7a51772d51
Create Date: 2024-10-27 22:57:25.638997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd89cf527a3'
down_revision: Union[str, None] = 'ef7a51772d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###