"""name of business_unit_added

Revision ID: 898f2e3c755d
Revises: 54eb5c55dcd5
Create Date: 2024-11-22 19:33:22.706103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898f2e3c755d'
down_revision: Union[str, None] = '54eb5c55dcd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_units', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_units', 'name')
    # ### end Alembic commands ###