"""new orders

Revision ID: b5b6dd7d3e43
Revises: 70390f294fa4
Create Date: 2024-11-13 21:09:11.135604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b6dd7d3e43'
down_revision: Union[str, None] = '70390f294fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_units', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('disciplines', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents_types', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('managements_areas', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managements_areas', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents_types', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('disciplines', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('business_units', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###