"""Creación de list sin relacion

Revision ID: d04be7ecc437
Revises: ccf35f497bf2
Create Date: 2024-10-31 16:25:42.947003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04be7ecc437'
down_revision: Union[str, None] = 'ccf35f497bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('disciplines_business_unit_uuid_fkey', 'disciplines', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('disciplines_business_unit_uuid_fkey', 'disciplines', 'business_units', ['business_unit_uuid'], ['uuid'])
    # ### end Alembic commands ###