"""adding column order

Revision ID: d644f51f6135
Revises: 3461cddc1572
Create Date: 2024-10-24 14:09:42.273300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd644f51f6135'
down_revision: Union[str, None] = '3461cddc1572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_units', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('disciplines', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('documents_types', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('managements_areas', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managements_areas', 'order')
    op.drop_column('documents_types', 'order')
    op.drop_column('disciplines', 'order')
    op.drop_column('business_units', 'order')
    # ### end Alembic commands ###