"""creacion de status_comment

Revision ID: de6c6cba0c65
Revises: 8df1e87893c5
Create Date: 2024-11-06 13:47:48.689342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6c6cba0c65'
down_revision: Union[str, None] = '8df1e87893c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_documents_correlative_logs', sa.Column('status_comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_documents_correlative_logs', 'status_comment')
    # ### end Alembic commands ###