"""Adding project_document_correlative_log2

Revision ID: ef7a51772d51
Revises: b04542fa5e63
Create Date: 2024-10-27 21:19:00.686653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef7a51772d51'
down_revision: Union[str, None] = 'b04542fa5e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_documents_correlative_logs',
    sa.Column('uuid', sa.UUID(as_uuid=150), nullable=False),
    sa.Column('project_document_correlative_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('file_uuid', sa.UUID(as_uuid=200), nullable=True),
    sa.Column('upload_by', sa.String(length=255), nullable=True),
    sa.Column('upload_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('status_by', sa.String(length=255), nullable=True),
    sa.Column('status_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_uuid'], ['files.uuid'], ),
    sa.ForeignKeyConstraint(['project_document_correlative_uuid'], ['project_documents_correlative.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_project_documents_correlative_logs_uuid'), 'project_documents_correlative_logs', ['uuid'], unique=False)
    op.drop_constraint('project_documents_correlative_file_uuid_fkey', 'project_documents_correlative', type_='foreignkey')
    op.drop_column('project_documents_correlative', 'upload_at')
    op.drop_column('project_documents_correlative', 'upload_by')
    op.drop_column('project_documents_correlative', 'file_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_documents_correlative', sa.Column('file_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('project_documents_correlative', sa.Column('upload_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('project_documents_correlative', sa.Column('upload_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key('project_documents_correlative_file_uuid_fkey', 'project_documents_correlative', 'files', ['file_uuid'], ['uuid'])
    op.drop_index(op.f('ix_project_documents_correlative_logs_uuid'), table_name='project_documents_correlative_logs')
    op.drop_table('project_documents_correlative_logs')
    # ### end Alembic commands ###