"""Creación de nro y name

Revision ID: f6501bbe96fa
Revises: ac91e9f4214a
Create Date: 2024-10-22 18:08:01.869513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6501bbe96fa'
down_revision: Union[str, None] = 'ac91e9f4214a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_versions', sa.Column('nro', sa.String(length=255), nullable=True))
    op.drop_column('documents_versions', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_versions', sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('documents_versions', 'nro')
    # ### end Alembic commands ###