from app.models.BusinessUnit import BusinessUnit
from app.models.Disciplines import Discipline
from app.models.Document import Document
from app.models.DocumentType import DocumentType
from app.models.DocumentVersion import DocumentVersion
from app.models.File import File_tb
from app.models.ManagementAreas import ManagementArea
from app.models.ProjectDocument import ProjectDocument
from app.models.ProjectDocumentCorrelative import ProjectDocumentCorrelative
from app.models.ProjectDocumentCorrelativeLogs import ProjectDocumentCorrelativeLog